services:
  api:
    container_name: wheat_api
    build:
      context: ./server
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./runs:/runs
      - ./results:/results
    environment:
      - DATA_DIR=/data
      - RUNS_DIR=/runs
      - RESULTS_DIR=/results
    restart: unless-stopped

  app:
    container_name: wheat_app
    build:
      context: ./apps
    ports:
      - "8501:8501"
    # volumes:
    #   - ../data:/data
    #   - ../runs:/runs
    #   - ../results:/results
    environment:
      # - DATA_DIR=/data
      # - RUNS_DIR=/runs
      # - RESULTS_DIR=/results
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
